apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: hotel-rating
spec:
  selector:
    app: service-registry
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: hotel-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: hotel-rating/service-registry:latest
          imagePullPolicy: Always
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-registry
          ports:
            - containerPort: 8084
