server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: HOTEL_SERVICE

  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka : true
    service-url:
      defaultZone: http://localhost:8084/eureka


